// Generated by CoffeeScript 1.8.0
(function() {
  var handle, port, requestHandlers, router, server;

  server = require('./server');

  router = require('./router');

  requestHandlers = require('./requestHandlers');

  process.on('uncaughtException', function(error) {
    return console.dir(error);
  });

  handle = {};

  handle['/'] = requestHandlers.index;

  handle['/index'] = requestHandlers.index;

  handle['/query'] = requestHandlers.query;

  port = 8000;

  server.start(router.route, handle, port);

}).call(this);
