// Generated by CoffeeScript 1.8.0
(function() {
  var route;

  route = function(handle, path, request, response) {
    console.log("About to route a request for " + path);
    if (typeof handle[path] === 'function') {
      return handle[path](request, response);
    } else {
      response.writeHead(404, {
        "Content-Type": "text/html;charset=UTF-8"
      });
      response.write("404 Not found");
      return response.end();
    }
  };

  exports.route = route;

}).call(this);
