// Generated by CoffeeScript 1.8.0
(function() {
  var http, start, url;

  http = require('http');

  url = require('url');

  start = function(route, handle, port) {
    var onRequest;
    onRequest = function(request, response) {
      var path;
      path = url.parse(request.url).path;
      return route(handle, path, request, response);
    };
    http.createServer(onRequest).listen(port);
    return console.log("Server has started @" + port + ".");
  };

  exports.start = start;

}).call(this);
